#默认使用配置
spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

  freemarker:
    cache: true


server:
  port: 8443
  ssl:
    key-store: /media/chenjunan/D/Idea-workspace/xianhuamao/src/main/resources/server.keystore
    key-alias: jetty
    key-store-type: jks
    key-store-password: chenjunan
    enabled: true


http:
  port: 8080


#公共配置与ｐｒｏｆｉｌｅｓ无关:
mybatis:
  type-aliases-package: com.xianhuamao.pojo
  mapper-locations: classpath:mappers/*.xml
